server:
  address: 127.0.0.1
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      persistent: true
      store-dir: ${ROCKETSHOW_SESSION_DIR:./sessions}
      timeout: 40d
      cookie:
        max-age: 30d

spring:
  data:
    rest:
      base-path: api
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${ROCKETSHOW_UPLOAD_TMP_DIR:./upload-tmp}